packages:
  - .

allowBuilds:
  esbuild: true

overrides:
  'source-map-js@>=1.0.0 <1.2.2': 1.2.2
  'esbuild@>=0.27.3 <0.28.1': 0.28.1
  'nanoid@>=3.0.0 <3.3.18': 3.3.18
  'vite@>=7.0.0 <=7.3.4': 7.3.5
